print('what do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call a astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock knock.')
input()
print('Interrupting cow.')
input()
print('Interruping cow wh', end='')
print('-MOO!')

